### ISSUE TITLE
Semicolons left in the source sass

### ISSUE THREAD

**Issue by Viratak** [Wikiki/bulma-slider#56]
I'm using bulma and bulma extensions with Angular / sass and quite a lot of custom variables hence the need to use source sass files from both bulma and bulma-extensions.

By trying to run my angular site it throwed me this error : 
```
SassError: semicolons aren't allowed in the indented syntax.
   ╷
86 │                 vertical-align: middle;
   │                                       ^
   ╵
  node_modules\bulma-extensions\bulma-slider\src\sass\index.sass 86:27  @import
  node_modules\bulma-extensions\src\sass\index.sass 14:9                @import
  shared\styles\variables.sass 86:9                                     @import
  app\components\main.sass 1:9                                          root stylesheet
```

I went to the given file and quickly found the issue: two semicolons are left (while not allowed in sass indented syntax) **lines 86 and 91**

I guess it's not really an "error" since some sass processors allow for semicolons but mine is a bit sensitive and since these are not required they could just be removed

**Comment by Wikiki** [comment]
Hi @Viratak,

To start as mentionned in `bulma-extensions` readme the bulma-extensions repository is not maintained anymore and you have to use the dedicated extension repository (this one for bulma-slider).

For the semicolon issue it has already been fixed with the PR #40.
Make sure to use the last released version of `bulma-slider` package.
